# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "home"
  url = "#home"
  weight = 1

[[main]]
  name = "about"
  url = ""
  identifier = "about"
  weight = 2

[[main]]
  name = "our clients"
  url = "clients/"
  parent = "about"

[[main]]
  name = "our core team"
   url = "team/"
  parent = "about"

[[main]]
  name = "analytics"
  url = "analytics/"
  weight = 3

# [[main]]
#   name = "training"
#   url = "#training"
#   weight = 4

[[main]]
  name = "contact us"
  url = "contact-us/"
  weight = 5


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
